// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApc7y5YmPgwOqcZj-Ivmp_CK4hxNwu3Hc',
    appId: '1:544878014081:web:c084a77f9ed0e710dde780',
    messagingSenderId: '544878014081',
    projectId: 'pyplant-4712a',
    authDomain: 'pyplant-4712a.firebaseapp.com',
    storageBucket: 'pyplant-4712a.appspot.com',
    measurementId: 'G-69PHRWKXVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOMjUfEgyEdq2z3lmIhUYOESKtsGvMnho',
    appId: '1:544878014081:android:cc13f62a59e276d1dde780',
    messagingSenderId: '544878014081',
    projectId: 'pyplant-4712a',
    storageBucket: 'pyplant-4712a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI3LHCJMa4oIbWa36eAjuL5jGDuH3qMPc',
    appId: '1:544878014081:ios:210b34cfcb5e9e82dde780',
    messagingSenderId: '544878014081',
    projectId: 'pyplant-4712a',
    storageBucket: 'pyplant-4712a.appspot.com',
    iosBundleId: 'com.example.pyplant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI3LHCJMa4oIbWa36eAjuL5jGDuH3qMPc',
    appId: '1:544878014081:ios:210b34cfcb5e9e82dde780',
    messagingSenderId: '544878014081',
    projectId: 'pyplant-4712a',
    storageBucket: 'pyplant-4712a.appspot.com',
    iosBundleId: 'com.example.pyplant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApc7y5YmPgwOqcZj-Ivmp_CK4hxNwu3Hc',
    appId: '1:544878014081:web:884595e0b9bc5feedde780',
    messagingSenderId: '544878014081',
    projectId: 'pyplant-4712a',
    authDomain: 'pyplant-4712a.firebaseapp.com',
    storageBucket: 'pyplant-4712a.appspot.com',
    measurementId: 'G-VHSBBW48WN',
  );
}
